server:
  port: ${SERVER_PORT:8098}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:service-postgres}
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/test?currentSchema=un}
    username: ${DATASOURCE_NAME:test}
    password: ${DATASOURCE_PASSWORD:test}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: un
  flyway:
    schemas: un
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,readiness,liveness
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: "service-postgres"

springdoc:
  api-docs:
    path: /api/v3/api-docs
  swagger-ui:
    path: /api/swagger-ui.html