server:
  port: ${SERVER_PORT:8098}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:service-postgres}
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/test?currentSchema=un}
    username: ${DATASOURCE_NAME:test}
    password: ${DATASOURCE_PASSWORD:test}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: ${DEFAULT_SCHEMA:un}
  flyway:
    schemas: ${DEFAULT_SCHEMA:un}
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:/}
    connection-timeout: ${RABBITMQ_CON_TIMEOUT:5000}

app:
  un:
    billing-queue: ${BILLING_QUEUE:billing.checks.queue}
    daily-cron: ${DAILY_CRON:0 34 3 * * *}
    retry-delay: ${RETRY_DELAY:5000}


management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,readiness,liveness
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: "service-postgres"

springdoc:
  api-docs:
    path: /api/v3/api-docs
  swagger-ui:
    path: /api/swagger-ui.html